### PR TITLE
A couple of fixes to Buy signs

### PR DESCRIPTION
**Pull request by NathanWolf**
This mainly fixes selling a field for virtual currency, which was causing an NPE in the purchase payment log.

I also made it so the buy sign doesn't drop when purchased. I ran into a strange issue where it dropped as a "broken" item (log spawn with invalid item in entity, item looks like stone). I'm not sure why this was, but I kind of figured the sign isn't part of the purchase anyway - feel free to change that bit if you want, of course! :)

### CODE REVIEW

**Comment by marcelo-mason** [comment]
Perfect, thanks.  Yeah sign doesn't matter, good call.

**Comment by marcelo-mason** [comment]
FYI Gonna reformat the code to Java standards.  Pull the next commit if you wanna do any more changes as all the files will be drastically changed.

**Comment by NathanWolf** [comment]
Thanks for the head's up!

It's funny, I was actually thinking to myself "finally, another dev who loves C-style bracing and doesn't mind throwing Java standards to the wind!" ;)

**Comment by marcelo-mason** [comment]
Hahaha, yeah that's exactly the way I felt forever since I code C# for work.  But then they switch to the "One True Brace" style at work, throwing C# standards to the wind like a year ago which pissed me off immensely.  How dare they fly against C# standards like that, nobody writing C# does OTB style, so wtf.  Thats when I realized the hipocracy of my ways, being that I made it so difficult for all the people that contributed to my Java plugins over the years, so I decided to go back to the standards on my Java plugins lol.

**Comment by NathanWolf** [comment]
Ha- I'm the same way.. C-style bracing is just easier for me to read, but hard to go against conventions. My plugin is actually a sad mix of the two, I really need to mass reformat.

I may embark on some more extensive changes, I'm a little intimidated to try and add new flags, but I think I may need one for "owner can't move field"?

Let me know if you'd like to see what I'm doing with this- we're setting up something pretty cool, with deep integration with quests and magic spells :)

**Comment by marcelo-mason** [comment]
Definitely interested in what you guys are doing, let me know when you guys have something to show :)

This is the rundown of adding flags:

* Add it to *parseSettings* in `FieldSettings` (use the lowercase and dash version of the flag name as it will show in the config), also notice it is added differently if the flag is a boolean flag vs another type.  If its boolean you just call loadBoolean, otherwise you create an instance variable and a getter function.
* Add it to `FieldFlag` enum in order to be able to detect it inside fields using the enum i.e. FieldFlag.PREVENT_FIRE (not required if its a non-boolean flag with a getter function that only holds data i.e. *price* flag -- field.getSettings().getPrice())  (FYI the name on the enum should be same as the name of the flag on the config but all uppercase and with an underscore instead of dash)
* If it applies to non-allowed players by default (i.e. prevent break), add it to *applyToNonAllowed* list on the same `FieldFlag` file.

That's basically it.


```

```

**Pull request merged**
