### PR TITLE
Update snapshot download link

### PR DESCRIPTION
**Pull request by RoboMWM**
Update: Just noticed that your jenkins doesn't publish the artifacts shortly after PRing this. I guess you no longer provide downloads to snapshots? 

---

Btw, it seems I wasn't able to build it on my machine due to it trying to find dependencies which don't exist in your maven repo? https://gist.github.com/RoboMWM/46a1349b89f8042f7f069e556cb7c0f3

### CODE REVIEW

**Comment by MDelgadoCCM** [comment]
It should, must be broke.  Will fix.

**Comment by marcelo-mason** [comment]
Fixed it, it was a config issue.

**Comment by RoboMWM** [comment]
FYI, this PR is changing the "download" link in the readme to point to your CI. Do you not want that?

**Comment by marcelo-mason** [comment]
thanks, ticket closed by itself from commit message

**Pull request merged**
